name: doctor_module
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  country_code_picker: ^3.0.0
  flutter_bounce: ^1.1.0
  country_picker: ^2.0.26
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.3.2
  percent_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/




  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix: null

